"""Self-contained interactive HTML, with embedded Plotly and no network calls."""
import json
from pathlib import Path
from plotly.offline import get_plotlyjs


def write_report(result, path):
    payload = json.dumps(result, allow_nan=False).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    template = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SeqGain · sequencing effort</title><style>
:root{font-family:system-ui,sans-serif;color:#193238;background:#eff4f2;color-scheme:light}*{box-sizing:border-box}
body{margin:0}header{background:#123d42;color:white;padding:36px max(24px,calc((100vw - 1240px)/2))}
header p{color:#c1ded6;max-width:850px}h1{font-size:40px;margin:10px 0}h2{font-size:23px;margin:0 0 12px}
main{max-width:1288px;margin:auto;padding:24px}section,.card{background:white;border:1px solid #d6e3df;border-radius:12px;padding:24px;margin-bottom:20px}
.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{margin:0 0 20px}.value{font-size:28px;font-weight:650;margin:8px 0}
.sub,p,li{line-height:1.55}.sub{color:#52676c;font-size:14px}.controls{display:flex;flex-wrap:wrap;gap:20px;align-items:center;margin:16px 0}
select,button{font:inherit;padding:9px 12px;border-radius:6px;border:1px solid #8fa8a1;background:white}input{accent-color:#087d75;min-width:260px}input[type=checkbox]{min-width:0}
button{cursor:pointer;background:#123d42;color:white}label{display:flex;gap:12px;align-items:center}.chart{height:390px}.notice{background:#fff3d9;border-left:4px solid #d99931;padding:14px;line-height:1.5}
table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:12px;border-bottom:1px solid #dae5e1}th{color:#52676c}.tablewrap{overflow:auto}
details{margin:16px 0}summary{cursor:pointer;font-weight:600}code{font-size:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere}
@media(max-width:760px){.cards{grid-template-columns:1fr}.card{margin-bottom:0}header{padding:24px}h1{font-size:32px}main{padding:12px}section{padding:16px}.chart{height:330px}}
</style><script>__PLOTLY__</script></head><body>
<header><div>SEQGAIN / SEQUENCING EFFORT</div><h1 id="name"></h1><p>How much does more sequencing buy you? Explore sequence discovery alongside reference breadth, with every segment kept visible.</p></header>
<main><div class="notice">Research-use scenarios, not validated stopping rules. Beyond 2× effort, predictions depend increasingly on model assumptions; retrospective 2× checks do not validate a 100× scenario. Replicate traces are not confidence intervals.</div><div class="controls"><label>Plot range: 0–<input id="horizon" type="range" min="2" max="100" step="1" value="2"><strong id="horizonvalue">2×</strong></label></div><br>
<div class="cards"><div class="card"><div class="sub">REFERENCES</div><div class="value" id="referencecount"></div><div class="sub">All computations run locally</div></div>
<div class="card"><div class="sub">SEQUENCE DISCOVERY</div><div class="value" id="distinct"></div><div class="sub" id="kinfo"></div></div>
<div class="card"><div class="sub">OBSERVED MEAN DEPTH</div><div class="value" id="meandepth"></div><div class="sub">Length-weighted across selected references</div></div></div>
<section id="ksection"><h2>K-mer discovery</h2><p class="sub">Canonical, quality-filtered k-mers; one incidence per fragment, including both mates. Singletons remain visible because removing them can hide real rare sequence.</p><div id="kchart" class="chart"></div><p id="ksummary" class="sub"></p><p id="kdiagnostics" class="sub"></p></section>
<section id="bsection"><h2>Reference coverage</h2><div class="controls"><label>Reference view <select id="segment"></select></label><label>Minimum depth <input id="threshold" type="range" min="1" max="100" value="10" step="1"><strong id="depthvalue">10×</strong></label></div><div id="bchart" class="chart"></div><p id="fitinfo" class="sub"></p><div class="tablewrap"><table><thead><tr><th>Reference</th><th>Length</th><th>Mean fragment coverage</th><th id="breadthheading">Breadth ≥10×</th></tr></thead><tbody id="coveragerows"></tbody></table></div><p class="sub">The all-references row is length-weighted over every selected reference, including zero-coverage bases. Overlapping mates count once, so fragment coverage can be lower than read coverage.</p></section>
<section><h2>Explore additional sequencing</h2><div class="controls"><label>Total effort <input id="slider" type="range" min="100" max="200" value="150" step="1"><strong id="multiple">1.50×</strong></label></div>
<p id="scenario"></p><div class="tablewrap"><table><thead><tr><th>Group / segment</th><th>Minimum depth</th><th>Observed breadth</th><th>Scenario breadth</th><th>Fit status</th></tr></thead><tbody id="rows"></tbody></table></div>
<p class="sub">Read these signals together: increasing breadth with little new k-mer discovery can still justify target sequencing. Strong k-mer discovery with flat target breadth may reflect non-target organisms, errors, or target mapping gaps. Whole-metagenome discovery cannot certify a focal organism’s completeness.</p></section>
<section><h2>Assumptions and diagnostics</h2><ul id="warnings"></ul><details><summary>Methods</summary><p>Reference: accessible-fraction gamma–Poisson depth model; deterministic nested fragment subsamples. K-mers: incidence Chao2 lower-bound richness and anchored incidence extrapolation. Phred scores provide a conservative expected error burden but do not change the raw counts or forecast. Reference forecasts are shown independently; no acceptance criterion or sequencing recommendation is applied. Forecasts assume unchanged sample composition and library behavior.</p><p>See the accompanying README and docs/methods.md for equations, filtering, limitations and references.</p></details><details><summary>Run provenance</summary><pre id="provenance"></pre></details><button id="download">Download results JSON</button></section>
</main><script id="data" type="application/json">__DATA__</script><script>
const d=JSON.parse(document.getElementById('data').textContent),k=d.kmers;
let b=d.bam;
const $=id=>document.getElementById(id), fmt=n=>Number(n).toLocaleString(undefined,{maximumFractionDigits:0}), pct=n=>(n*100).toFixed(1)+'%';
const layout=(ylabel)=>({margin:{l:65,r:20,t:20,b:55},paper_bgcolor:'white',plot_bgcolor:'white',font:{family:'system-ui',color:'#193238'},xaxis:{title:{text:'Fraction of current sequencing effort'},range:[0,+$('horizon').value*1.01],gridcolor:'#e5eeeb'},yaxis:{title:{text:ylabel},gridcolor:'#e5eeeb'},legend:{orientation:'h',y:1.15},hovermode:'x unified'});
const config={responsive:true,displaylogo:false,modeBarButtonsToRemove:['sendDataToCloud','sendChartToCloud'],toImageButtonOptions:{format:'svg'}};
const trace=(x,y,name,dash,color)=>({x,y,name,mode:'lines',line:{dash:dash||'solid',color:color||'#087d75',width:2}});
$('name').textContent=d.sample;$('distinct').textContent=k?fmt(k.distinct):'Not supplied';$('kinfo').textContent=k?`k=${k.k} · ${fmt(k.fragments)} fragments · source: ${k.source||'FASTQ'}`:'Enable BAM or FASTQ discovery with --kmer-source';
let targets=b?b.targets:[], overall=b?b.summary:null, views=b?[overall,...targets]:[];
$('referencecount').textContent=b?fmt(targets.length):'Not supplied';
$('meandepth').textContent=b?fullRow(overall).mean_fragment_depth.toFixed(2)+'×':'Not supplied';
if(k){let traces=[];for(let r=0;r<d.parameters.replicates;r++){let rows=k.curves.filter(x=>x.replicate===r);traces.push(trace(rows.map(x=>x.fraction),rows.map(x=>x.distinct),'Subsample '+(r+1),'solid',r?'#a7ccc2':'#087d75'));}
traces.push(trace(k.forecast.points.map(x=>x.effort),k.forecast.points.map(x=>x.distinct),'Incidence scenario','dot','#d58b2a'));Plotly.newPlot('kchart',traces,layout('Distinct canonical k-mers'),config);
$('ksummary').textContent=`${fmt(k.singletons)} singleton k-mers; ${fmt(k.recurrent_distinct)} seen in ≥2 fragments. Chao2 richness lower-bound estimate: ${fmt(k.forecast.asymptote_lower_bound)}. This is not an estimated genome size.`;
$('kdiagnostics').textContent=`Phred-derived upper estimate: ${k.phred_error.expected_false_singletons_upper.toFixed(1)} of the singleton k-mers and ${k.phred_error.expected_false_distinct_upper.toFixed(1)} distinct k-mers lack an error-free fragment support. Raw counts and forecasts are unchanged.`+(k.retrospective_backtests.length?` Retrospective 2× checks: maximum absolute relative error ${(Math.max(...k.retrospective_backtests.map(x=>Math.abs(x.relative_error)))*100).toFixed(1)}%.`:``);
}else{$('ksection').hidden=true}
function fullRow(t){return t.curves.find(x=>x.replicate===0&&x.fraction===1)}
function forecast(t,n){let source=t.model||t;return source.forecast_breadth&&source.forecast_breadth[n]?[source.forecast_efforts,source.forecast_breadth[n]]:null}
function drawCoverageRows(n){$('breadthheading').textContent='Breadth ≥'+n+'×';$('coveragerows').replaceChildren();views.forEach((s,i)=>{let row=document.createElement('tr'),full=fullRow(s),name=i===0?'All references':s.group+' / '+s.contig;if(i===0)row.style.fontWeight='650';[name,fmt(s.length),full.mean_fragment_depth.toFixed(2)+'×',pct(full.breadth[n])].forEach(v=>{let cell=document.createElement('td');cell.textContent=v;row.append(cell)});$('coveragerows').append(row)})}
function drawB(){let t=views[+$('segment').value],n=$('threshold').value,traces=[];$('depthvalue').textContent=n+'×';for(let r=0;r<d.parameters.replicates;r++){let rows=t.curves.filter(x=>x.replicate===r);traces.push(trace(rows.map(x=>x.fraction),rows.map(x=>x.breadth[n]),'Subsample '+(r+1),'solid',r?'#a7ccc2':'#087d75'))}
let f=forecast(t,n);if(f)traces.push(trace(f[0],f[1],'Anchored '+n+'× scenario','dot','#d58b2a'));
let l=layout('Reference breadth');l.yaxis.range=[0,1.02];l.yaxis.tickformat='.0%';Plotly.react('bchart',traces,l,config);
$('fitinfo').textContent=!t.model?'All references combined by reference length; the scenario is the matching weighted combination of anchored reference forecasts.':t.model.status==='no_coverage'?'No usable coverage: no forecast.':`Fit: ${t.model.status}; RMSE ${(t.model.rmse*100).toFixed(2)} percentage points; held-out full-effort error ${(t.model.holdout_max_absolute_error*100).toFixed(2)} points.`+(t.model.retrospective_backtests.length?` Retrospective 2× maximum error ${(Math.max(...t.model.retrospective_backtests.map(x=>x.max_absolute_error))*100).toFixed(2)} points.`:``)+` Every scenario is conditioned on and anchored to the measured breadth at current effort.`;drawCoverageRows(n);scenario()}
if(b){$('segment').add(new Option('All references',0));targets.forEach((t,i)=>$('segment').add(new Option(t.group+' / '+t.contig,i+1)));$('segment').onchange=drawB;$('threshold').oninput=drawB;
let variants=[d.bam,...(d.bam_filter_variants||[])],definition=b.coverage_definition,filters=document.createElement('div');filters.className='controls';
let maplabel=document.createElement('label'),mapselect=document.createElement('select');mapselect.id='mapq';maplabel.append('Minimum MAPQ ',mapselect);
[...new Set(variants.map(v=>v.coverage_definition.minimum_mapq))].sort((a,b)=>a-b).forEach(q=>mapselect.add(new Option(q,q)));mapselect.value=definition.minimum_mapq;
let duplabel=document.createElement('label'),dupcheck=document.createElement('input');dupcheck.id='duplicates';dupcheck.type='checkbox';dupcheck.checked=definition.include_marked_duplicates;duplabel.append(dupcheck,'Include marked duplicates');filters.append(maplabel,duplabel);
let note=document.createElement('p');note.className='sub';note.textContent='MAPQ filters alignment confidence; lower values admit more ambiguous mappings. MAPQ 255 (unknown) is always excluded. Duplicate filtering uses existing BAM flags, not new duplicate detection. These controls affect all reference coverage, forecasts and diagnostics; k-mer discovery is unchanged. '+(variants.length>1?'Only precomputed settings are available; switching is instant and offline.':'Filters are fixed for this report. Run with --explore-filters to enable these controls.');
mapselect.disabled=dupcheck.disabled=variants.length===1;$('bsection').insertBefore(filters,$('bsection').children[1]);filters.after(note);
function selectFilters(){b=variants.find(v=>v.coverage_definition.minimum_mapq===+mapselect.value&&v.coverage_definition.include_marked_duplicates===dupcheck.checked);targets=b.targets;overall=b.summary;views=[overall,...targets];$('meandepth').textContent=fullRow(overall).mean_fragment_depth.toFixed(2)+'×';drawB();drawDiagnostics()}
mapselect.onchange=dupcheck.onchange=selectFilters;drawB()}else{$('bsection').hidden=true}
function interp(points,t,key){let hi=points.findIndex(p=>p.effort>=t);if(hi<0)return points.at(-1)[key];if(hi===0)return points[0][key];let a=points[hi-1],c=points[hi];return a[key]+(c[key]-a[key])*(t-a.effort)/(c.effort-a.effort)}
function scenario(){let t=+$('slider').value/100;$('multiple').textContent=t.toFixed(2)+'×';let msg=`${t.toFixed(2)}× the current sequencing amount, assuming unchanged composition.`;if(t>2)msg+=' Long-range scenario: not validated by the 2× retrospective checks.';if(k){let v=interp(k.forecast.points,t,'distinct');msg+=` Projected new k-mers: ${fmt(v-k.distinct)}.`;if(t<=99.9)msg+=` Increasing effort to ${(t+.1).toFixed(2)}× adds about ${fmt(interp(k.forecast.points,t+.1,'distinct')-v)} more k-mers.`;} $('scenario').textContent=msg;
$('rows').replaceChildren();let n=$('threshold').value;views.forEach(s=>{let row=document.createElement('tr'),obs=fullRow(s).breadth[n],f=forecast(s,n),pred=t===1?obs:f?interp(f[0].map((effort,i)=>({effort,breadth:f[1][i]})),t,'breadth'):null;[s.contig?s.group+' / '+s.contig:'All references',n+'×',pct(obs),pred===null?'Unavailable':pct(pred),s.model?s.model.status:'See individual reference diagnostics'].forEach(v=>{let cell=document.createElement('td');cell.textContent=v;row.append(cell)});$('rows').append(row)});if(b){let selected=views[+$('segment').value],f=forecast(selected,n),value=t===1?fullRow(selected).breadth[n]:f?interp(f[0].map((effort,i)=>({effort,breadth:f[1][i]})),t,'breadth'):null;$('scenario').textContent+=value===null?' No forecast available for this reference.': ' At '+t.toFixed(2)+'× effort, '+pct(value)+' of '+(selected.contig||'all selected references')+' '+(t===1?'has':'is estimated to reach')+' at least '+n+'× fragment depth.';}}
$('slider').oninput=scenario;scenario();
function drawDiagnostics(){let warnings=[...(k?k.warnings:[]),...(b?b.warnings:[]),...targets.flatMap(t=>t.model.warnings.map(w=>t.contig+': '+w))];$('warnings').replaceChildren();warnings.forEach(w=>{let li=document.createElement('li');li.textContent=w;$('warnings').append(li)});$('provenance').textContent=JSON.stringify({...d.provenance,reference_coverage:b?{definition:b.coverage_definition,record_counts:b.record_counts}:null},null,2)}
drawDiagnostics();
$('horizon').oninput=()=>{let h=+$('horizon').value;$('horizonvalue').textContent=h+'×';$('slider').max=h*100;$('slider').value=Math.min(+$('slider').value,h*100);if(k)Plotly.relayout('kchart',{'xaxis.range':[0,h*1.01]});if(b)drawB();scenario()};
$('download').onclick=()=>{let u=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='seqgain-results.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
</script></body></html>'''
    Path(path).write_text(template.replace("__PLOTLY__", get_plotlyjs()).replace("__DATA__", payload), encoding="utf-8")
